version: '3'

services:
  payment-service:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: payment-service
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev